/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import org.example.controller.UserAnalyticsController

fun main() {
    UserAnalyticsController.createApp().start(8080)
    while (true) Thread.currentThread().join()
}
